esphome:
  name: dht11
  platform: esp8266
  board: nodemcu
  project:
    name: "vcj.klint-land"
    version: "1.0.0"

ota:
  - platform: esphome
    password: !secret gen_password
    port: 8266

wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret gen_password
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
    - ssid: !secret wifi_ssid_3
      password: !secret wifi_password_3

  ap:
    ssid: !secret wifi_ssid_ap
    password: !@secret gen_password

web_server:
  port: 80
  version: 2

logger:
  level: DEBUG
# This file is used to configure the DHT11 sensor connected to the ESP8266

sensor:
  - platform: dht
    model: DHT11
    pin: GPIO2
    temperature:
      name: "Porche Temperature"
      id: porche_temperature
    humidity:
      name: "Porche Humidity"
      id: porche_humidity
    update_interval: 10min